# Generated by Django 2.1.4 on 2018-12-17 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='task',
            field=models.TextField(default='this is a new default'),
            preserve_default=False,
        ),
    ]
